### ISSUE TITLE
Bad handling of errors when rebasing

### ISSUE THREAD

**Issue by royger** [ctmarinas/stgit#34] opened 2019-07-19 09:31 UTC
Hello,

When rebasing a branch with local commits that lead to conflicts stgit will throw the following backtrace and crash:

```
% stg rebase upstream/staging
Checking for changes in the working directory ... done
Popping all applied patches ... done
Rebasing to "upstream/staging" ... done
Pushing patch "func_fn" ... done (empty patch)
Pushing patch "devfn_sbdf" ... done (empty patch)
Pushing patch "pdev_union" ... done (empty patch)
Pushing patch "pci_sbdf" ...
  CONFLICT (content): Merge conflict in xen/include/xen/pci.h
Error: The merge failed during "push".
       Revert the operation with "stg undo".
xen/include/xen/pci.h: unmerged (b03927cd28d85c2fe9325e9f8912c66990e3473d)
xen/include/xen/pci.h: unmerged (04a9f46cc32ffc56452efa022b03ea19d6e0f06a)
xen/include/xen/pci.h: unmerged (12f1cea19bc50738b64fac172cbbe6f41894b25a)
fatal: git-write-tree: error building trees
Traceback (most recent call last):
  File "/usr/local/bin/stg", line 47, in <module>
    main()
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/main.py", line 213, in main
    _main()
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/main.py", line 192, in _main
    directory.write_log(cmd)
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/commands/common.py", line 599, in write_log
    log.compat_log_entry(msg)
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/log.py", line 383, in compat_log_entry
    log_entry(Fakestack(stack), msg)
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/log.py", line 336, in log_entry
    new_log = LogEntry.from_stack(last_log, stack, msg)
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/log.py", line 191, in from_stack
    for pn in stack.patchorder.all),
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/log.py", line 191, in <genexpr>
    for pn in stack.patchorder.all),
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/log.py", line 366, in get
    return stack.patches.get(pn)
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/stack.py", line 189, in get
    return self.__patches[name]
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/git.py", line 569, in __getitem__
    self.__objects[name] = self.__create(name)
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/stack.py", line 179, in create_patch
    p.commit # raise exception if the patch doesn't exist
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/stack.py", line 34, in commit
    return self.__stack.repository.refs.get(self.__ref)
  File "/usr/local/Cellar/stgit/0.19/lib/python2.7/site-packages/stgit/lib/git.py", line 532, in get
    return self.__repository.get_commit(self.__refs[ref])
KeyError: u'refs/patches/pci_sbdf_t/add_fn_field'
```

**Comment by lkraav** [comment] 2019-07-19 13:15
Yes, tyvm for filing! I was on the edge of filing this myself today :)

`stg push` stops correctly with a "Merge conflict" state, but `stg rebase` became broken as described, somewhere in 0.18 ~> 0.19 transition.

**Comment by jpgrayson** [comment] 2019-07-20 02:38
Thanks for reporting this issue. There were definitely changes affecting `stg rebase` between 0.18 and 0.19, but also more major changes since 0.19 on master.

I'll take this moment to apologize since I am the one responsible for the breakage.

I've done an initial triage of the problem. I was not able to reproduce the exact same symptom, but I was able to produce a similar symptom on 0.19 as well as a more minor problem on master (incorrect return code).

I have just pushed a small change to master to repair the incorrect return code as well as introduce a new test case for `stg rebase` that triggers a rebase-time conflict.

It would be very helpful to me if either of you could test your rebase workflows with the code from master. One big warning: the master code increments the stgit metadata version, so you would have to export your patches, blow away the stgit stack, and re-import your patches to go back to the 0.19 (or 0.18) release version. I understand if this is too much trouble. if so, any additional detail you could offer about the state of your stack when this rebase fails would be appreciated.

**Comment by royger** [comment] 2019-08-14 13:16
Hello,

Sorry for not following up, would it be possible to get a release with this fix? It's quite an annoying bug, and would likely impact others.

Thanks, Roger.

**Comment by lkraav** [comment] 2019-08-14 19:01
Indeed, it would definitely be easier to test if the fix candidate was backported on top of 0.19-branch.

Alternatively, if new `master` had some kind of a stack migration / update functionality, that would also improve the ability to test a variety of scenarios much quicker.

**Comment by jpgrayson** [comment] 2019-08-19 22:17
> Indeed, it would definitely be easier to test if the fix candidate was backported on top of 0.19-branch.

Conversely, it would definitely be easier to fix if a test was forward-ported to `master`. ;-)

More seriously, there was a pretty big overhaul of `stg rebase` after the 0.19 release. Stgit currently has both an "old" and a "new" git interface library. `stg rebase` was changed to use the "new" git interface. So the "fix candidate" is this overhaul to the new interface. It's not really feasible to backport this change to 0.19 in isolation.

> Alternatively, if new master had some kind of a stack migration / update functionality, that would also improve the ability to test a variety of scenarios much quicker.

The stack migration is automatic when moving to a new stgit version. However there is no automation for migrating the stack version backward. Thus running with stgit `master` is easy; it's just that going back to 0.19 would take some effort. I run with `master` all the time and all the test cases are passing, so I'd say it's generally a safe thing to do.

Running with the latest stgit code to confirm/deny whether the issue is repaired would be the most helpful. Ultimately, this issue is going to be repaired on `master`, so testing `master` and developing a new test case on `master` (if the bug still persists) will be the most helpful.

I agree that we're due for a new stgit release. As was noted, it would be nice if this bug was repaired in the proposed release. But in order to know whether it is repaired, I could use some help from those who have experienced it.

**Comment by lkraav** [comment] 2019-08-25 14:42
I just tested, and it looks like the problem is fixed on current `master` :+1: 

```
leho@gusto /usr/src/pf-kernel.git-e7440 $ stg rebase linux/master 
Popping all applied patches ...                                                                           
  Popped makefile-extraversion-gentoo -- 4567_distro-Gentoo-Kconfig.patch
done                                                                                                      
Rebasing to "d1abaeb3be7b5fa6d7a1fbbd2e14e3310005c4c1" ... done                           
Pushing patch "4567_distro-Gentoo-Kconfig.patch" ... warning: inexact rename detection was skipped due to too many files.                                                                                            
warning: you may want to set your merge.renamelimit variable to at least 1699 and retry the command.
done (conflict)                                                                                                                                                                                                      
Error: 1 merge conflict(s)                                                                                                                                                                                           
       CONFLICT (content): Merge conflict in Kconfig                                                      
Now at patch "4567_distro-Gentoo-Kconfig.patch"
```

... whereas on 0.19 it would fail with `git-write-tree` as originally described here.

**Comment by jpgrayson** [comment] 2019-08-26 02:57
Thanks @lkraav for testing this on `master`. I'm glad it's better behaved now!

**Closed by jpgrayson** 2019-08-26 02:57 UTC
